#
# Variables needed by other make files.
#

LISPBOX_VERSION := 0.7
TOP             := /tmp
LISPBOX_HOME    := lispbox-$(LISPBOX_VERSION)
SH              := /bin/sh

os              := $(shell uname)
prefix          := $(TOP)/$(LISPBOX_HOME)
empty           :=
space           := $(empty) # don't remove this comment

export GZIP = -q

ifeq ($(os),CYGWIN_NT-5.1)
os := Windows
endif
